services:
  web:
    container_name: web
    image: pedrodev190/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - database
    env_file: .env
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - app
    depends_on:
      - web

  database:
    container_name: database
    image: mysql:latest
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql:
